services:
  postgres:
    image: postgres:17.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: SERVICE_NAME
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - v_postgres_data:/var/lib/postgresql/data

volumes:
  v_postgres_data:
