all:
  hosts:
    primary:
      ansible_host: 192.168.200.19
      ansible_become_password: ubuntu
      ansible_user: ubuntu
      ansible_password: ubuntu

    replica:
      ansible_host: 192.168.200.20
      ansible_become_password: ubuntu
      ansible_user: ubuntu
      ansible_password: ubuntu
