version: "3.9"

services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    entrypoint: sh
    env_file:
      - .env
    command: -c "
      minio server /data --address :9000 --console-address :9090;"
    volumes:
      - ./minio/data:/data
  minio_createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set minioio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      mc mb --ignore-existing minioio/${S3_BUCKET_NAME};
      mc anonymous set public minioio/${S3_BUCKET_NAME};
      exit 0;"
    env_file:
      - .env
