---
- name: Install psycopg2 using apt
  become: true
  apt:
    name: python3-psycopg2
    state: present

- name: Create replication user
  become: true
  become_user: postgres
  postgresql_user:
    name: "replicator"
    password: "replication_password"
    role_attr_flags: "REPLICATION"
    state: present
